language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_846414b03e16_key -iv $encrypted_846414b03e16_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
